# 배포 환경에서만 사용할 환경구성은 application-local.yml에 작성합니다.
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://donggrina-rds.cpiwm8seedtc.ap-northeast-2.rds.amazonaws.com:3306/donggrina?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: donggrina
    password: po9vah4i
  jpa:
    hibernate:
      ddl-auto: none
      format_sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect