# 로컬 환경에서만 사용할 환경구성은 application-local.yml에 작성합니다.
spring:
  config:
    activate:
      on-profile: local
    import: optional:file:.env[.properties]

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/donggrina
    username: ${DONGGRINA_LOCAL_DB_USERNAME}
    password: ${DONGGRINA_LOCAL_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
  data:
    redis:
      host: localhost
      port: 6379
  jwt:
    secret: anmslkfnagkljasnkdkmaslmglnmalsmdlkmaskngnasnmd123125tklnmekldgf
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 10MB

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${OAUTH2_KAKAO_CLIENT_ID}
            client-secret: ${OAUTH2_KAKAO_CLIENT_SECRET}
            redirect-uri: http://localhost:8080/members/login
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            scope:
              - profile_nickname
              - profile_image

          google:
            client-id: ${OAUTH2_GOOGLE_CLIENT_ID}
            client-secret: ${OAUTH2_GOOGLE_CLIENT_SECRET}
            redirect-uri: http://localhost:8080/members/login
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            scope:
              - profile
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
cloud:
  aws:
    s3:
      bucket: donggrina
    credentials:
      access-key: ${DONGGRINA_AWS_ACCESS_KEY}
      secret-key: ${DONGGRINA_AWS_SECRET_KEY}
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false

image:
  url:
    default:
      member: ${MEMBER_DEFAULT_IMAGE_URL}
      dog: ${DOG_DEFAULT_IMAGE_URL}
      cat: ${CAT_DEFAULT_IMAGE_URL}