name: Deploy To EC2 with using Docker

on:
  push:
    branches:
      - main
      - develop

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Github Repository 파일 불러오기
        uses: actions/checkout@v4

      - name: JDK17 버전 설치
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: application.properties 만들기
        run: echo "${{ secrets.APPLICATION }}" > ./src/main/resources/application.properties

      - name: 빌드하기
        run: ./gradlew clean build -x test -Pprod

      - name: AWS Resource에 접근할 수 있게 AWS credentials 설정
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ap-northeast-2
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: ECR 로그인
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Docker 이미지 생성
        run: docker build -t donggrina .

      - name: Docker 이미지에 Tag 붙이기
        run: docker tag donggrina ${{ steps.login-ecr.outputs.registry }}/donggrina:latest

      - name: ECR에 Docker 이미지 push
        run: docker push ${{ steps.login-ecr.outputs.registry }}/donggrina:latest

      - name: SSH로 EC2에 접속
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script_stop: true
          script: |
            docker stop donggrina || true 
            docker rm donggrina || true
            docker pull ${{ steps.login-ecr.outputs.registry }}/donggrina:latest
            docker run -d --name donggrina -p 8080:8080 ${{ steps.login-ecr.outputs.registry }}/donggrina:latest
